# Generated by Django 4.0.3 on 2022-06-10 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_defaultmodel_alter_user_options_user_friends_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefaultModel',
        ),
    ]
