# Generated by Django 4.0.3 on 2022-06-10 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_delete_defaultmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('icon', models.FileField(upload_to='icons/category/', verbose_name='Иконка')),
                ('order', models.PositiveSmallIntegerField(default=999, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.UUIDField(auto_created=True, verbose_name='Хэш доступа')),
                ('created_at', models.DateTimeField(auto_created=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('date', models.DateTimeField(null=True, verbose_name='Время встречи')),
                ('full_amount', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Обновлено')),
                ('title', models.CharField(blank=True, default='', max_length=64, verbose_name='Наименование')),
                ('amount', models.PositiveSmallIntegerField(default=0, verbose_name='Сумма')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='party.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Запись траты',
                'verbose_name_plural': 'Записи трат',
            },
        ),
        migrations.CreateModel(
            name='ParticipantsThroughModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Обновлено')),
                ('want_to', models.BooleanField(default=False, verbose_name='Собирается идти на встречу?')),
                ('came', models.BooleanField(default=False, verbose_name='Пришел на встречу?')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spending', to='party.group', verbose_name='Группа')),
                ('records', models.ManyToManyField(to='party.record')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spending', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Участие пользователей',
            },
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Обновлено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='party.group')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invites', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Приглашение',
                'verbose_name_plural': 'Приглашения',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(related_name='related_groups', through='party.ParticipantsThroughModel', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
